app:
  name: ui
  image:
    repository: onecx-apps/onecx-ai-management-ui
  routing:
    enabled: true
    path: /mfe/onecxAiUiManagement/
  operator:
    microfrontend:
      enabled: true
      specs:
        main:
          exposedModule: ./OnecxAiUiManagementModule
          description: OneCX OnecxAiUi Management Module
          note: OneCX OnecxAiUi Management UI module auto import via MF operator
          type: MODULE
          technology: WEBCOMPONENTMODULE
          remoteName: onecx-ai-management-ui
          tagName: onecx-ai-management-ui-webcomponent
    permission:
      enabled: true
      spec:
        permissions:
          AI_KNOWLEDGE_DOCUMENT:
            CREATE: Create AIKnowledgeDocument
            EDIT: Edit AIKnowledgeDocument
            DELETE: Delete AIKnowledgeDocument
            SAVE: Update and save AIKnowledgeDocument
            IMPORT: Import AIKnowledgeDocument
            EXPORT: Export AIKnowledgeDocument
            VIEW: View mode for AIKnowledgeDocument
            SEARCH: Search AIKnowledgeDocument
          AI_KNOWLEDGE_VECTOR_DB:
            CREATE: Create AIKnowledgeVectorDb
            EDIT: Edit AIKnowledgeVectorDb
            DELETE: Delete AIKnowledgeVectorDb
            SAVE: Update and save AIKnowledgeVectorDb
            IMPORT: Import AIKnowledgeVectorDb
            EXPORT: Export AIKnowledgeVectorDb
            VIEW: View mode for AIKnowledgeVectorDb
            SEARCH: Search AIKnowledgeVectorDb
            BACK: Go Back AIKnowledgeVectorDb
          AI_PROVIDER:
            CREATE: Create AIProvider
            EDIT: Edit AIProvider
            DELETE: Delete AIProvider
            SAVE: Update and save AIProvider
            IMPORT: Import AIProvider
            EXPORT: Export AIProvider
            VIEW: View mode for AIProvider
            SEARCH: Search AIProvider
            CHANGE_API_KEY: Change ApiKey AIProvider
          AI_CONTEXT:
            CREATE: Create aiContext
            EDIT: Edit aiContext
            DELETE: Delete aiContext
            SAVE: Update and save aiContext
            IMPORT: Import aiContext
            EXPORT: Export aiContext
            VIEW: View mode for aiContext
            SEARCH: Search aiContext
            BACK: Back to aiContext
          AI_KNOWLEDGE_BASE:
            CREATE: Create AIKnowledgeBase
            EDIT: Edit AIKnowledgeBase
            DELETE: Delete AIKnowledgeBase
            SAVE: Update and save AIKnowledgeBase
            IMPORT: Import AIKnowledgeBase
            EXPORT: Export AIKnowledgeBase
            VIEW: View mode for AIKnowledgeBase
            SEARCH: Search AIKnowledgeBase
            BACK: Back to AIKnowledgeBase
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            clientId: onecx-ai-management-ui
